spring.application.name=volos-beer-service
vb.brewery.beer-inventory-service-host=http://localhost:8082

#Logging
logging.level.gr=debug
#logging.level.org.springframework.jdbc.datasource.init=DEBUG
#logging.level.org.springframework.boot.sql.init=DEBUG

#SQL data Initialization
spring.sql.init.mode=never
#spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Datasource
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MYSQL
spring.h2.console.enabled=true

#activemq-artemis docker image
spring.artemis.user=artemis
spring.artemis.password=artemis



