spring.application.name=volos-beer-service
logging.level.gr=debug
vb.brewery.beer-inventory-service-host=http://localhost:8082


spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.jdbc.datasource.init=DEBUG
logging.level.org.springframework.boot.sql.init=DEBUG
